class FileSystemEnum:
    PROJECT = 'pobrema'
    FILE_EXTENSION = '.py'
    KEY = 'key'
    LOCK = 'lock'
    INIT_FILE = f'__init__{FILE_EXTENSION}'
    TAG_SYMBOL = '%'
    SRC = 'src'
    EXERCICIOS = 'exercicios'
    SCAFFOLD = 'scaffold'
    TEMPLATE_REPOSITORY = 'template_repository'
    TEMPLATES = 'templates'
    LOCK_TEMPLATE = 'lock_template'
    PROBLEM_TEMPLATE = 'problem_template'
    KEY_TEMPLATE = 'key_template'
    PROBLEM_INIT_TEMPLATE = 'problem_init_template'
    KEY_INIT_TEMPLPATE = 'key_init_template'
